"
This class contains tests ? Eh bien non , elle hérite de testCase mais ne dispose d'aucune méthode de test çàd pas une seule méthode commençant par test
"
Class {
	#name : #ApurgerTest,
	#superclass : #TestCase,
	#category : #'MyPlanDEau-Tests'
}

{ #category : #tests }
ApurgerTest >> EssaiTest [
	"comment stating purpose of instance-side method"
	"scope: class-variables  &  instance-variables"	
			
	| temporary variable names |
	^ self
]

{ #category : #tests }
ApurgerTest >> testEssai [
	"comment stating purpose of instance-side method"
	"scope: class-variables  &  instance-variables"	
			
	| temporary variable names |
	^ self
]
